#
# Get CIMS defaults
#
if [ -r /usr/local/lib/.system.kshrc ] ; then
    . /usr/local/lib/.system.kshrc
fi


# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/zsh/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
# ZSH_THEME="darkblood"
# ZSH_THEME="ys"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# ZSH options
unsetopt autopushd
zmodload zsh/mathfunc


__git_files () { 
    _wanted files expl 'local files' _files     
}


###########################################################################
#                         Madrespek Modifications                         #
###########################################################################

export DOTFILES="$HOME/.dotfiles"


#   Ipython completion
source $DOTFILES/ipython-completion.bash

#######USER ALIASES########################

alias prox='ssh -YD 9999 ndb245@access.cims.nyu.edu'
alias webd="cd ~/Sites/"
alias ssh='ssh -Y'
alias mnt_helix='sshfs -o transform_symlinks,follow_symlinks helix: /Users/noah/shares/helix'
alias aria='aria2c -d $HOME/Desktop -j 4 -x 4 --load-cookies=$HOME/.cookies -Z'
alias fserve='aria2c -d $HOME/Downloads/Warez -j 4 -x 4 --load-cookies=$HOME/.cookies -Z'
alias ipy='ipython qtconsole --pylab=inline'

alias screen='screen -R'
alias p='pushd'
alias o='popd' 
alias d='dirs -v'

alias ipynb='ipython notebook --browser=no'

if [[ $(uname) == "Darwin" ]] 
then
    alias g='mvim --servername VIM1 --remote-silent'
    alias mlab='/Applications/MATLAB_R2013a.app/bin/matlab -nodesktop -nosplash'
    alias vim='mvim -v'
    alias marked="open -a Marked.app"
    alias emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"

else
    alias g='gvim --servername VIM1 --remote-silent'
    alias mlab='matlab -nodisplay'
    alias vim='vim -X'
fi
    


if [[ $(hostname) == *.cims.nyu.edu ]]
then
    source $DOTFILES/zsh/cims.zsh
fi


###########################################################################
#                         Environmental Variables                         #
###########################################################################

export PATH=/Library/Frameworks/EPD64.framework/Versions/Current/bin:/usr/local/bin:/Users/noah/.dotfiles/dotsync/bin:/Users/noah/local/bin:/Applications/Wine.app/Contents/Resources/bin/:/opt/ncl_ncarg/bin:/Users/noah/usr/bin:/Users/noah/bin/nbconvert-master:/Users/noah/.cabal/bin:/usr/local/texlive/2010/bin/x86_64-darwin:/Users/noah/bin:/usr/local/share/python:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:$PATH
export PATH=/usr/local/texlive/2010/bin/x86_64-darwin:$HOME/bin:/usr/local/share/python:$PATH
export PATH=$HOME/usr/bin:$HOME/bin/nbconvert-master:$HOME/.cabal/bin:$PATH
export PATH=/opt/ncl_ncarg/bin:$PATH
export PATH=/Applications/Wine.app/Contents/Resources/bin/:$PATH
export PATH=$HOME/local/bin:$PATH
export PATH=/Applications/git-annex.app/Contents/MacOS:$PATH

export EDITOR='/usr/bin/env vim'
export NCARG_ROOT=/opt/ncl_ncarg
export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.8:$PKG_CONFIG_PATH

export DOTFILES=$HOME/.dotfiles
export PATH=$DOTFILES/dotsync/bin:$PATH
export PATH=/usr/local/pkg/emacs/24.3/bin:$PATH

export PATH=/usr/local/texlive/2013/bin/x86_64-linux/:$PATH

export PYTHONPATH=$DOTFILES/python:$PYTHONPATH

export ETS_TOOLKIT=qt4

if [[ $(uname) == 'Darwin' ]]
then
    export PATH=/usr/local/bin:/anaconda/bin:$PATH
    export PATH=/Applications/git-annex.app/Contents/MacOS:$PATH


    # VIRTUAL_ENV_DISABLE_PROMPT=1 source /Users/noah/Library/Enthought/Canopy_64bit/User/bin/activate

    # Setting PATH for EPD-7.3-2
    # The orginal version is saved in .bash_profile.pysave
    export PATH
    export PYTHONPATH=/Users/noah/proj/rayben:$PYTHONPATH
    alias pynb='cd ~/Dropbox/ipython-notebooks && tmux new "ipython notebook"'

    MKL_NUM_THREADS=1
    export MKL_NUM_THREADS
    export PATH=/opt/local/bin:$PATH
fi


